sudo simple_switch_CLI --thrift-port 9090 <../flow_table/flow_table/s1_s1.txt
sudo simple_switch_CLI --thrift-port 9091 <../flow_table/flow_table/s1_s2.txt
sudo simple_switch_CLI --thrift-port 9092 <../flow_table/flow_table/s2_s1.txt
sudo simple_switch_CLI --thrift-port 9093 <../flow_table/flow_table/s2_s2.txt
sudo simple_switch_CLI --thrift-port 9094 <../flow_table/flow_table/p1_l1.txt
sudo simple_switch_CLI --thrift-port 9095 <../flow_table/flow_table/p1_l2.txt
sudo simple_switch_CLI --thrift-port 9096 <../flow_table/flow_table/p2_l1.txt
sudo simple_switch_CLI --thrift-port 9097 <../flow_table/flow_table/p2_l2.txt
sudo simple_switch_CLI --thrift-port 9098 <../flow_table/flow_table/p3_l1.txt
sudo simple_switch_CLI --thrift-port 9099 <../flow_table/flow_table/p3_l2.txt
sudo simple_switch_CLI --thrift-port 9100 <../flow_table/flow_table/p4_l1.txt
sudo simple_switch_CLI --thrift-port 9101 <../flow_table/flow_table/p4_l2.txt
sudo simple_switch_CLI --thrift-port 9102 <../flow_table/flow_table/p1_t1.txt
sudo simple_switch_CLI --thrift-port 9103 <../flow_table/flow_table/p1_t2.txt
sudo simple_switch_CLI --thrift-port 9104 <../flow_table/flow_table/p2_t1.txt
sudo simple_switch_CLI --thrift-port 9105 <../flow_table/flow_table/p2_t2.txt
sudo simple_switch_CLI --thrift-port 9106 <../flow_table/flow_table/p3_t1.txt
sudo simple_switch_CLI --thrift-port 9107 <../flow_table/flow_table/p3_t2.txt
sudo simple_switch_CLI --thrift-port 9108 <../flow_table/flow_table/p4_t1.txt
sudo simple_switch_CLI --thrift-port 9109 <../flow_table/flow_table/p4_t2.txt
